version: "3.9"
services:
  react-app:
    build: 
      dockerfile: Dockerfile.react
    ports:
      - "80:80"
    networks:
      - blog-app

  json-server:
    build: 
      dockerfile: Dockerfile.json-server
    ports:
      - "8000:8000"
    networks:
      - blog-app

networks:
  blog-app:
    driver: bridge
