name: Pull Request Actions
on:
  push:
  pull_request:
    branches: [master]
    
env:
  artifact_name: app_ver_${{ github.sha }}

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}
      - name: Install packages
        if: steps.cache-npm.outputs.cache-hit != 'true'
        id: install
        run: npm ci

  report_install:
    if: failure()
    runs-on: ubuntu-20.04
    needs: [install]
    steps:
      - name: send message if INSTALL fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FIX IT!! CI FAILED!!
            ${{ github.actor }} created commit:
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
  test:
    runs-on: ubuntu-20.04
    needs: [install]
    steps:
      - uses: actions/checkout@v3

      - name: Use cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - name: Test
        run: npm run test

  report_test:
    if: failure()
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: send message if TEST fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FIX IT!! TEST FAILED!!
            ${{ github.actor }} created commit:
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      
  lint:
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - uses: actions/checkout@v3

      - name: Use cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

      - name: Lint
        run: npm run lint

  report_lint:
    if: failure()
    runs-on: ubuntu-20.04
    needs: [lint]
    steps:
      - name: send message if LINT fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FIX IT!! LINT FAILED!!
            ${{ github.actor }} created commit:
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
  build:
    runs-on: ubuntu-20.04
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      
      - name: Use cached node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}
      
      - name: Build
        run: npm run build
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ env.artifact_name }}
          path: build
          retention-days: 1
          
  report_build:
    if: failure()
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: send message if BUILD fail
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FIX IT!! BUILD FAILED!!
            ${{ github.actor }} created commit:
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
  export_build:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ${{ env.artifact_name }}
          
      - name: try to archive folder
        run: cd /home/runner/work/Just-blog | zip -r ../../../../artifacts.zip Just-blog/
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: artifacts.zip
          message: |
            GOT IT!
            See changes: https://github.com/${{ github.repository }}

    
  
  
