name: Pull Request Actions
on:
  push:
  pull_request:
    branches: [master]
    
env:
  artifact_name: app_ver_${{ github.sha }}

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test

  report_test:
    if: failure()
    runs-on: ubuntu-latest
    needs: [install_and_test]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FIX IT!! TEST FAILED!!
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  build:
    runs-on: ubuntu-latest
    needs: [install_and_test]
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      
      - name: Build
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm run build
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: $ {{ env.artifact_name }}
          retention_days: 1
          
  report_build:
    if: failure()
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            FIX IT!! BUILD FAILED!!
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
  export_build:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: $ {{ env.artifact_name }}
          
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: $ {{ env.artifact_name }}
          message: |
            GOT IT!
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        

    
  
  
